name: Push

on:
  push:
    branches:
      - main
      - stable/2023.1
      - stable/2023.2
      - stable/2024.1

jobs:
  modified_rocks:
    uses: ./.github/workflows/modified_rocks.yaml

  build-and-publish:
    needs: modified_rocks
    uses: ./.github/workflows/build_publish.yaml
    with:
      rocks: ${{ needs.modified_rocks.outputs.rocks }}
      publish: true
      branch: ${{ github.ref }}
